datadog:
  timeboards: []
  monitors: []

  # Standard timeboard definitions
  timeboard_definitions:
    ServiceHealth:
      foo: bar

  # Standard monitor definitions
  monitor_definitions:
    HighLatencyP90:
      foo: bar
    High4XX:
      name: Service ${self `info.serviceName`} has a high 4xx rate on env:${self `info.stageName`}
      type: query alert
      query: avg(last_10m):sum:trace.http.request.hits.by_http_status{http.status_class:400,http.status_code:401,http.status_code:403,env:${self `info.stageName`},service:${self `info.serviceName`}}.as_count() / sum:trace.http.request.hits{env:${self `info.stageName`},service:${self `info.serviceName`}}.as_count() > ${self `datadog.monitor_definitions.High4XX.options.thresholds.warning`}
      message: |
        ##`{{service.name}}` 4xx rate is too high.

        {{^is_recovery}}
        - To troubleshoot, check the `{{service.name}}` [service page](https://app.datadoghq.com/apm/service/{{service.name}}/http.request?env=${self `info.stageName`}) or [recent traces](https://app.datadoghq.com/apm/traces?service={{service.name}}&name=http.request&env=${self `info.stageName`}) or [logs](https://service.au.sumologic.com/ui/index.html#section/search/%40%40_index%3Dlfscnpcom_cloudwatch%7Cwhere%20service_name%3D%22{{service.name}}%22%7Cwhere%20msg_log_level%3D%22ERROR%22).

        - For more information about the {{service.name}} check the [repository](https://github.latitudefinancial.com/Latitude/{{service.name}})
        {{/is_recovery}}

        {{#is_alert}}
        ${if eq "prod" (self `info.stageName`) }@pagerduty-CORE_API${end}
        {{/is_alert}}

        {{#is_alert_recovery}}
        ${if eq "prod" (self `info.stageName`) }@pagerduty-CORE_API${end}
        {{/is_alert_recovery}}

        @slack-api-alarm-${self `info.stageName`}
      tags:
        - env:${self `info.stageName`}
        - service:${self `info.serviceName`}
      options:
        notify_audit: false
        locked: false
        timeout_h: 0
        silenced: {}
        include_tags: true
        no_data_timeframe: null
        require_full_window: false
        new_host_delay: 300
        notify_no_data: false
        renotify_interval: 0
        escalation_message: ''
        thresholds:
          warning: 0.2
          critical: 0.3

    HighErrors:
      foo: bar
